### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by phil-isaacs** [MichaelZaporozhets/abstractconnect#4]
Hey Micheal,

First off thank you so much for making this project. I'd been looking for a way to do this exactly thing but hadn't found / figured out how to do it on my own.

Anyhow, I'm anxious to dig into it and actually learn how this works.

But I'm having an issue getting running.

I'm on a Mac Book Pro / OS X 10.15.3 and using Sketch with Abstarct.

For Node I'm using v10.18.1 and npm v6.13.4

Anyhow, when I run `yarn install` on the project I get this error.

```
     npm ERR! abstractconnect@1.1.2 fixACLIPath: `mkdir dist/bin && ln -s $(pwd)/node_modules/@elasticprojects/abstract-cli/bin/abstract-cli $(pwd)/dist/bin/abstract-cli`
npm ERR! Exit status 1

```

Is this because I'm using an older version of Node perhaps.

Thanks so much in advance,

Philip

**Comment by phil-isaacs** [comment]
Opps never mind. I figured it out on my own. For some reason my local environment had trouble with making the `dist/bin` folder.

I just ran the commands by hand and all is well.

**Comment by PierrickGT** [comment]
This issue should be reopened, I have the same problem with NPM and the latest version (v14.6.0 with npm 6.14.6) of Node.
