### ISSUE TITLE
Error when downloading file "Error: End of data reached"

### ISSUE THREAD

**Issue by phil-isaacs** [MichaelZaporozhets/abstractconnect#7]
Hey Micheal,

Just want to say thanks again for putting this package together.

I've been trying to use it as part of a pipeline I've been working on and I've run into a weird bug.

When I run my code, it works as expected but then dies and throws and error every time just after it downloads the sketch file from Abstract. The odd thing is the file downloads but I still get an error which stops the script from running.

```
abstractconnect: downloading data... ==

getSymbols Error:  Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at i.checkIndex (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:1:81628)
    at i.checkOffset (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:1:81541)
    at i.readData (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:9:145410)
    at i.readString (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:1:82048)
    at c.isSignature (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:9:140730)
    at c.readEndOfCentral (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:9:142975)
    at c.load (/Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:9:144722)
    at /Users/phil.isaacs/Sites/abstractconnect-fork/dist/main.js:9:139726
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Now if I rerun the script again it works perfectly because the getSketchFile function checks for the existing file first and then returns the path back to the script correctly. But unfortunately this would break our pipeline and unless I can figure out some correction for it.

As far as I can tell the issue seems to be right around the call to Sketch.fromFile() on line 78 of the src/index.js script. But, I can't seem to pinpoint the error since it looks like it's returning a promise so I would assume it would wait to finish before continuing.

I've tried a couple of things to try and fix it myself including upgrading the `abstract-cli` lib and the of course where I think the problem is coming from `sketch-constructor`. But still no luck.

Anyhow here is my script that is failing.

```
function makeTokens(){

   getSymbols({})
        .then(Symbols => {

            const tokens = Object.keys(Symbols);

            tokens.forEach(t => {
                let layer = Symbols[t].layers;
                designTokens.push(layer);
            });

        }).then( async() => {

            let tokens = await makeObj(designTokens);

            // This creates the CTI structure that Style Dictionary is looking for.
            let cat = {};
            cat[category] = {}
            let obj = cat[category][type] = {};
            cat[category][type] = tokens;

            fs.appendFile(dir + "/" + file, JSON.stringify(cat), function(err,data) { 
                if (err) {
                    return console.log("appendFile Error: ",err);
                }
            });
        })
        .catch(err => console.log("getSymbols Error: ", err));

}

```

Ok, thanks so much in advance.

Philip

**Comment by MichaelZaporozhets** [comment]
@phil-isaacs how serendipitous! I was just doing some maintenance/upgrading to this package. 

The abstract-cli package has actually gone through a bunch of upgrades itself, so perhaps once I publish this update (in the next hour or so) your issue will be resolved.

**Comment by MichaelZaporozhets** [comment]
@phil-isaacs I've just published v1.2.0, try that- please let me know if your issue persists.

**Comment by phil-isaacs** [comment]
> @phil-isaacs I've just published v1.2.0, try that- please let me know if your issue persists.

Hey @MichaelZaporozhets,

Thanks so much for the quick response. I upgraded this morning and it seems like the error is gone and my file is working! 

That's great, thank you so much.

I did notice one small different now, in that the temp file no longer saves on my computer. I'm not sure if that is expected behavior or not since it looks like the src still includes the check for existing sketch files. (line 49 getSketchFileWithFS). The temp directory is their but just remains empty. Although it's nice to have the file saved locally I don't think it's a big deal.

Philip

**Comment by phil-isaacs** [comment]
Oh wait. It helps to read the Readme.md. My bad

`withFS: force download to FS (ends up in the TEMP_PATH setup var below)`

**Comment by MichaelZaporozhets** [comment]
@phil-isaacs great to hear! And haha, yes- minor change there. I actually added the non-fs mode to amzn/sketch-constructor for this very purpose. In general, if we can avoid writing to the file system by default, we should. Better practice/more deterministic.

**Comment by phil-isaacs** [comment]
Hey Michael, one more quick question. 

When I pass the `getSymbols({withFS: true})` in my function it should force it to download the save the temp file like before? Is that correct or am I misunderstanding something.

**Comment by MichaelZaporozhets** [comment]
@phil-isaacs yes it should- is it not? I’ll double check it now.

Probably a good time for me to write some unit tests too to help avoid these sorts of bungles!
